package:
  name: unrar
  version: 7.11.0
  epoch: 0
  description: "UnRAR - free utility for RAR archives"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - ./packages
    packages:
      - build-base
      - busybox

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/aawc/unrar/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 36e1049633e6f048c25979d19a7b062fb29f280b7017eb6dcc11d9d59b244ab2
  - if: ${{build.arch}} == 'aarch64'
    uses: autoconf/make
    with:
      opts: CXXFLAGS="-march=armv8-a+crypto+crc -O2 -std=c++11 -Wno-logical-op-parentheses -Wno-switch -Wno-dangling-else"
  - if: ${{build.arch}} == 'x86_64'
    uses: autoconf/make
  - uses: autoconf/make-install
    with:
      opts: DESTDIR="${{targets.destdir}}/usr"
  - uses: strip

update:
  enabled: true
  github:
    identifier: aawc/unrar
    use-tag: true
